name: Extract Keystore Base64 for Persistent Signing

on:
  workflow_dispatch: # يتيح لك تشغيل هذا السكريبت يدوياً بنقرة زر من تبويب Actions

jobs:
  generate-keystore:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Generate Keystore & Convert to Base64
        run: |
          # 1. إنشاء ملف المفتاح بمعايير أمان عالية وببيانات ثابته
          keytool -genkeypair -v -keystore release.keystore -alias saydali_key -keyalg RSA -keysize 2048 -validity 10000 -storepass "SaydaliPass123" -keypass "SaydaliPass123" -dname "CN=DaftarAldeyon, OU=Dev, O=App, L=Basra, S=Basra, C=IQ" -storetype PKCS12

          # 2. طباعة النص المشفر بصيغة Base64 لتسهيل النسخ
          echo "==================== COPY START ===================="
          base64 -w 0 release.keystore
          echo -e "\n==================== COPY END ===================="
